### ISSUE TITLE
Compilation errors if we import EditorModule from tinymce-angular(1.0.8) in angular4

### ISSUE THREAD

**Issue by Gauravchandna007** [tinymce/tinymce-angular#14]
I am trying integrate tinymce to my application.

I have used **npm install @tinymce/tinymce-angular**

Then I imported editor module to Aappmodule.js and added EditorModule in imports.

After saving it I am getting the blow compilation error and blank page shown with error in console(Uncaught Error: Unexpected value 'EditorModule' imported by the module 'AppModule'. Please add a @NgModule annotation):-

`WARNING in ./node_modules/@tinymce/tinymce-angular/node_modules/@angular/core/esm5/core.js
6590:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\dependencies\ImportContextDependency.js:28:4)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\Users\mRoads\Desktop\Projects\panna-frontend\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

Angular version:- 4
Tinymce:- 1.0.8

**Comment by fyrkant** [comment]
Yes, probably. I haven't really tried out using the EditorModule in different versions of Angular, I'm not really sure how to keep it up to date as well as work with older versions... 🤔
